### ISSUE TITLE
Error creating assembly archive jar-with-dependencies: error in opening zip file 

### ISSUE THREAD

**Issue by alegrm** [AKSW/FOX#15]
Hi, 
I'm trying to build FOX from the last commit (51715e8fa9ad24c468e1f15d87c49cf96166c57b), and now on a server. And, I 'm getting an error:

ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5:single (default) on project fox: Failed to create assembly: Error creating assembly archive jar-with-dependencies: error in opening zip file -> [Help 1]
[1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

If I follow the maven help, seems there may be some authentication to perform against repositories. However I cannot find which one. 

Any idea?
Thanks in advance.

**Comment by renespeck** [comment]
Hi, 

did you run the 'build.sh' script?

**Comment by alegrm** [comment]
I was only doing maven. I tried the bulid and got:

17 Sep 2015 10:34:38 ERROR Fox - Could not load class: org.aksw.fox.tools.ner.en.OpenNLPEN
org.aksw.fox.data.exception.LoadingNotPossibleException: Could not load class: org.aksw.fox.tools.ner.en.OpenNLPEN

**Comment by renespeck** [comment]
For the English version of FOX, I suggest to checkout the  'en' branch, because the current documentation, readmes and wiki is for this version. 

If you want to use the 'master' branch you have to configure many files and there is no documentation at the moment, but soon.

Build master branch:
1. clone the branch
2. copy fox.properties-dist to fox.properties
3. run the build.sh script or 'mvn clean package'

Run FOX you have to:
4. configure the files in data/fox/cfg to your needs
5. install, configure extern tools if needed (e.g.: TagMe apikey, TextPro )
6. train a model for the language you aiming for if needed (with the default configuration, FOX comes with a trained models for 'en' and 'de', more models come soon)

I hope that helps.

If you still get an error, write what you exactly did, thanks.
